# Generated by Django 4.1 on 2022-09-27 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
