# Generated by Django 4.1 on 2022-10-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0003_alter_sessiondetails_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondetails',
            name='created_on',
            field=models.BigIntegerField(default=1664871449.995221),
        ),
    ]
