# Generated by Django 4.1 on 2022-10-04 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0005_alter_sessiondetails_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='userID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
