# Generated by Django 4.1 on 2022-09-27 19:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginPage.logindetails')),
            ],
        ),
    ]
