# Generated by Django 4.1 on 2022-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0002_sessiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondetails',
            name='created_on',
            field=models.BigIntegerField(default=1664814497.172933, editable=False),
        ),
    ]
