# Generated by Django 4.1 on 2022-10-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registersessiondetails',
            old_name='userID',
            new_name='regUserID',
        ),
    ]
