# Generated by Django 4.1 on 2022-10-15 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSessionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regSessionID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.BigIntegerField(editable=False)),
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('authCode', models.CharField(max_length=5)),
            ],
        ),
    ]
