# Generated by Django 4.1 on 2022-10-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_tweetdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdb',
            name='created_on',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
