# Generated by Django 4.1 on 2022-10-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.UUIDField(editable=False)),
                ('username', models.CharField(max_length=20)),
                ('userTag', models.CharField(max_length=4)),
            ],
        ),
    ]
